### ISSUE TITLE
你好，希望支持自定义下载目录

### ISSUE THREAD

**Issue by jerry011235** [XhstormR/GetBilibili#1]
你好，1.希望类似you-get做个支持自定义下载目录 比如： -o E:\视频
2.希望支持自动捕获bilibili视频名称作为下载的flv的文件名。

**Comment by XhstormR** [comment]
OK，我加到 TODO 里。

**Comment by jerry011235** [comment]
谢谢，刚才看到有人发了 [哔哩哔哩唧唧Chrome扩展程序 ](https://chrome.google.com/webstore/detail/%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E5%94%A7%E5%94%A7chrome%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F/kkbeponpcponmcikbgongkmhkbifocpf)，官网为：http://www.bilibilijj.com/  ，试用了下，发现它下载后能自动转成mp4格式，也希望GetBilibili支持。

**Comment by XhstormR** [comment]
已加至 TODO。

**Comment by XhstormR** [comment]
上述功能都已完成。
