### ISSUE TITLE
你好，当GetBilibili.jar的路径为中文时，下载会出现乱码文件夹。

### ISSUE THREAD

**Issue by jerry011235** [XhstormR/GetBilibili#2]
经过测试
`java -jar D:\安装程序和压缩包\s视频下载\GetBilibili.jar -d http://www.bilibili.com/video/av6335200/ 1 E:\视频`
这样会在D盘根目录生成一个`%e5%ae%89%e8%a3%85%e7%a8%8b%e5%ba%8f%e5%92%8c%e5%8e%8b%e7%bc%a9%e5%8c%85`文件夹；
而
`java -jar D:\others\GetBilibili.jar -d http://www.bilibili.com/video/av6335200/ 1 E:\视频` 则不会生成乱码文件夹，虽然两者都能完美下载转换视频。

**Comment by XhstormR** [comment]
这个问题我明天有时间的话看看。

**Comment by XhstormR** [comment]
你看看 v2.5.1 解决没有。

**Comment by jerry011235** [comment]
感谢，完美解决。果然是字符编码问题。
还有一个小细节，就是用ffmpeg转换时，中文路径仍然是乱码，这个不知能解决否？
![sp160922_210736](https://cloud.githubusercontent.com/assets/12509976/18749284/bd0fd2e4-8108-11e6-8109-92b3659834be.png)

**Comment by XhstormR** [comment]
在控制台执行 `chcp 65001` ，更改字符集后，就不会乱码了。

**Comment by jerry011235** [comment]
你好，似乎不行。
`String path = URLDecoder.decode(GetBilibili.class.getProtectionDomain().getCodeSource().getLocation().getPath(), "utf-8");`这个都加了utf-8，要不在“GetBilibili.java”里搜索“path”，一共25条结果，都加上utf-8试一试？（比如finalFilePath）

**Comment by XhstormR** [comment]
这个不是代码问题，是 `控制台的编码` 跟 `ffmpeg的编码` 不一致导致的。

你把 `控制台的编码` 变为 65001(`chcp 65001`)，跟 `ffmpeg的编码` 一样后，就不会乱码了。

![123](https://cloud.githubusercontent.com/assets/10527522/18774123/7a39b2e8-8188-11e6-9b42-1aab16f1a6d8.png)

我的建议是最好不要放在中文目录下。

**Comment by jerry011235** [comment]
好的，了解了，感谢，关闭问题吧。
