### ISSUE TITLE
优化缓存逻辑

### ISSUE THREAD

**Issue by jilulu** [XhstormR/GetBilibili#5]
[此处](https://github.com/XhstormR/GetBilibili/blob/master/src/GetBilibili.java#L67)个人认为不应该用APPDATA这个OS相关的路径。

上一行代码会在 macOS 下返回 ```null```，再下面``` new File(null, “GetBilibili")```时则会```nullpointer```。

**Comment by XhstormR** [comment]
嗯，我只考虑了 Windows 系统。

Mac 系统应该只能用 `-l` 选项，因为后面的下载与合并我用的是 Windows 下的 FFmpeg。

我会优化下逻辑，把创建文件夹的操作放在下载与合并中。

**Comment by XhstormR** [comment]
完成。
