### ISSUE TITLE
指定了Cookie仍无法下载承包番剧的1080p视频

### ISSUE THREAD

**Issue by shikkoku** [XhstormR/GetBilibili#6]
D:\Java>java -jar GetBilibili.jar -l http://bangumi.bilibili.com/anime/6000/play#103286

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -2
        at java.lang.String.substring(Unknown Source)
        at GetBilibili.getCID(GetBilibili.kt:170)
        at GetBilibili.generateLink(GetBilibili.kt:111)
        at GetBilibili.main(GetBilibili.kt:70)

**Comment by XhstormR** [comment]
现在 KEY 已经被封了，所以这种方式不行了。你可以试试通过 JSON、XML 解析。

```
java -jar GetBilibili.jar -l "https://bangumi.bilibili.com/player/web_api/playurl?cid=16505192&appkey=84956560bc028eb7&otype=json&type=&quality=4&module=bangumi&sign=beb058fbbcce512e6e237d578d8c47a4"
```

**Comment by shikkoku** [comment]
`https://bangumi.bilibili.com/player/web_api……`这种连接应该怎么获取？

**Comment by shikkoku** [comment]
链接在Chrome开发者工具里的网络选项卡过滤到了。不过还是下不了会员的1080p。

**Comment by XhstormR** [comment]
@shikkoku 需要你本身是会员才行的。

**Comment by shikkoku** [comment]
好吧，等大佬你的TODO搞定就完美了。我还是比较希望尽快支持合并成mp4的。使用这个下载速度远比you-get和yk-dl快。

**Comment by XhstormR** [comment]
@shikkoku 在命令中加入 `-convert` 选项就能合并为 MP4 格式了啊。

另外 TODO 在几个月前就完成了，当时都能用；只不过随着 KEY 被封，Bilibili 改版，一些解析类的功能不能用了，不过，够用就行。

**Comment by shikkoku** [comment]
我指定了cookie还是下不了1080p……

**Comment by XhstormR** [comment]
@shikkoku 你是大会员吗？

普通会员是不行的，也就是说你在网页上选择不了 1080P 的话，GetBilibili 一样也是不行的。

**Comment by shikkoku** [comment]
普通会员，但通过单部番剧支付B币（承包）可以获得1080p的播放权限。支付后单部番剧所有分集解锁1080p选项（网页及客户端都可选择1080p）。目前我使用Windows 10下的官方UWP客户端来下载1080p视频（4个flv分part文件）。

**Comment by XhstormR** [comment]
@shikkoku 我现在不是大会员，不能测试。

不过按道理说，选择 1080P 格式的 json或xml 文件，再指定 自己的 Cookie，应该是行的。

**Comment by shikkoku** [comment]
或者你提到cookie是要哪种格式的？我当时用的是Firefox的cookies.sqlite文件。

**Comment by XhstormR** [comment]
从这里面获得 Cookie：
![123](https://cloud.githubusercontent.com/assets/10527522/25522279/e78e2066-2c34-11e7-95d2-03ab29cf2878.png)

https://github.com/XhstormR/GetBilibili/blob/master/src/main/kotlin/GetBilibili.kt#L39
后面的注释是我当时是大会员时，1080P测试成功所需要的 Cookie 值。

现在不知道更新没，把全部 Cookie 附上去吧。

**Comment by shikkoku** [comment]
值可以指定txt文件还是直接贴这一串？

**Comment by shikkoku** [comment]
指定后可以下载1080p了。不过要贴一大串略麻烦就是了……

**Comment by XhstormR** [comment]
@shikkoku 你可以试试只指定我注释中指定的 Cookie，看看格式是否还是这样。

https://github.com/XhstormR/GetBilibili/blob/master/src/main/kotlin/GetBilibili.kt#L39

**Comment by shikkoku** [comment]
不行，虽然有部分格式仍然一样，但是选用你给出的类似格式段无效。没有sid=字段了。

**Comment by XhstormR** [comment]
@shikkoku 嗯，更新了，那就只有排除法一个个试了，要么就全部都贴上。

**Comment by shikkoku** [comment]
找出来还麻烦，还不如一段贴上去。希望以后能直接指定一个外部cookie文本。

**Comment by XhstormR** [comment]
@shikkoku 等 `2017.10.10` 我领大会员的时候吧，现在够用就行：）

**Comment by shikkoku** [comment]
对了，ffmpeg库是内嵌的？好像和我path里设置的版本不一样。

**Comment by XhstormR** [comment]
@shikkoku 是内置的。

**Comment by XhstormR** [comment]
@shikkoku 

版本更新了，已增加此功能：

命令行添加 `-cookie`，然后将 Cookie 写入 Jar 目录下的 cookie.txt 即可。
