### ISSUE TITLE
作者好，请问还有更加详细一些的教程吗？

### ISSUE THREAD

**Issue by zasl** [XhstormR/GetBilibili#7]
本人有点小白，想用这个工具下载b站电影，但是不会用，从昨天到今天研究，连一部电影都无法获取，55555

**Comment by XhstormR** [comment]
```
java -jar GetBilibili.jar -l "https://interface.bilibili.com/playurl?cid=11239800&ts=1477907912&player=1&sign=d47cc63f6ca756e3d9b806b7068df18b"
```

上面这条命令能够正常执行吗？

如果上面的执行没有问题的话，就可以用 F12 查看 Network 面板，搜索带有 playurl 关键字的链接，把这个链接传给 GetBilibili 就可以了。

另外因为没有 KEY 了，所以不能直接用这样的链接 `http://www.bilibili.com/video/av6896579/`，而是应该用上面这样的链接。
