### ISSUE TITLE
原视频不能解析了吗？

### ISSUE THREAD

**Issue by cutelittleturtle** [XhstormR/GetBilibili#9]
运行 .jar -l url
结果：Total Size: 0.00 MB (0,000 bytes)	Total Time: 00:00:00 (00:00 Mins)

**Comment by XhstormR** [comment]
你用的 URL 是什么？

**Comment by cutelittleturtle** [comment]
原视频url, av12345那样的。

source code里面generateLink()好像就只检查了"playurl" && "json"和"playurl"。可能我没找到解析原url的地方。。

**Comment by XhstormR** [comment]
因为没有 KEY 了，所以现在不能直接分析这样的链接了 http://www.bilibili.com/video/av6896579 。 

现在的权宜之计是用 F12 查看 Network 面板，搜索带有 playurl 关键字的链接，把这个链接传给 GetBilibili 就可以了。

等会我去更新 README。

**Comment by cutelittleturtle** [comment]
原来如此 T T
https://loadercdn.io/ 这个api好像可以解析b站视频诶。

**Comment by cutelittleturtle** [comment]
明白了，谢谢解释！

2018-01-14 0:09 GMT-06:00 XhstormR <notifications@github.com>:
